platform :ios, '16.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

IOS_DEPS = File.expand_path('../ios-deps', __dir__)
require_relative "#{IOS_DEPS}/@capacitor/ios/scripts/pods_helpers"

# Fonction pour ajouter les plugins Capacitor nécessaires
def capacitor_pods
   pod 'Alamofire', '5.10.2'
   pod 'EcoveloSDK', :git => 'https://github.com/titibike/ecovelo-sdk-ios.git', :tag => '1.0.1'
   pod 'Capacitor', :path => "#{IOS_DEPS}/@capacitor/ios"
   pod 'CapacitorCordova', :path => "#{IOS_DEPS}/@capacitor/ios"  
   pod 'CapacitorCommunityNativeAudio', :path => "#{IOS_DEPS}/@capacitor-community/native-audio"
   pod 'CapacitorCommunityStripe', :path => "#{IOS_DEPS}/@capacitor-community/stripe"
   pod 'CapacitorMlkitBarcodeScanning', :path => "#{IOS_DEPS}/@capacitor-mlkit/barcode-scanning"
   pod 'CapacitorApp', :path => "#{IOS_DEPS}/@capacitor/app"
   pod 'CapacitorAppLauncher', :path => "#{IOS_DEPS}/@capacitor/app-launcher"
   pod 'CapacitorBrowser', :path => "#{IOS_DEPS}/@capacitor/browser"
   pod 'CapacitorCamera', :path => "#{IOS_DEPS}/@capacitor/camera"
   pod 'CapacitorFilesystem', :path => "#{IOS_DEPS}/@capacitor/filesystem"
   pod 'CapacitorGeolocation', :path => "#{IOS_DEPS}/@capacitor/geolocation"
   pod 'CapacitorHaptics', :path => "#{IOS_DEPS}/@capacitor/haptics"
   pod 'CapacitorKeyboard', :path => "#{IOS_DEPS}/@capacitor/keyboard"
   pod 'CapacitorPreferences', :path => "#{IOS_DEPS}/@capacitor/preferences"
   pod 'CapacitorPushNotifications', :path => "#{IOS_DEPS}/@capacitor/push-notifications"
   pod 'CapacitorScreenOrientation', :path => "#{IOS_DEPS}/@capacitor/screen-orientation"
   pod 'CapacitorStatusBar', :path => "#{IOS_DEPS}/@capacitor/status-bar"
   pod 'CapawesomeCapacitorLiveUpdate', :path => "#{IOS_DEPS}/@capawesome/capacitor-live-update"
   pod 'SentryCapacitor', :path => "#{IOS_DEPS}/@sentry/capacitor"
   pod 'CapacitorNativeSettings', :path => "#{IOS_DEPS}/capacitor-native-settings"
   pod 'CapacitorPluginAppTrackingTransparency', :path => "#{IOS_DEPS}/capacitor-plugin-app-tracking-transparency"
  pod 'Firebase/CoreOnly'
  pod 'Firebase/Messaging'
  pod 'Firebase/Installations'
  pod 'GoogleDataTransport'
  pod 'GoogleUtilities'
  pod 'nanopb'
end


# Définir l'intégration du SDK Ecovelo
target 'sample-app' do
  capacitor_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['DEAD_CODE_STRIPPING'] = 'NO'
    end
  end
end

